package csci305.javalab;

/*  CSCI 305 Lab 3 - Java Lab
 *  Rock, Paper, Scissors, Lizard, Spock
 *  Nate Tranel - njtranel@gmail.com
 */

 //this class is just an example runner class that was part
 //of the assignment self-checks. None of this code was
 //generated by me. This was to test the Element class
 //and subclasses.
public class TestElements {

	//create instances of the Elements and test their comparator functions
	public static void main(String args[]) {
		Element rock = new Rock("Rock");
		Element paper = new Paper("Paper");
		System.out.println(rock.compareTo(paper));
		System.out.println(paper.compareTo(rock));
		System.out.println(rock.compareTo(rock));
	}
}
